import numpy as np

from pathlib import Path
from collections import OrderedDict

import pytest

from reader.sifter import Sifter, get_unique_label_values


@pytest.fixture
def segheader() -> dict:
    header = OrderedDict([
             ('type', 'unsigned char'),
             ('dimension', 4),
             ('space', 'left-posterior-superior'),
             ('sizes', np.array([  2, 570, 662, 643])),
             ('space directions',
              np.array([[np.nan, np.nan, np.nan],
                        [-0.125,  0.   ,  0.   ],
                        [ 0.   , -0.125,  0.   ],
                        [ 0.   ,  0.   ,  0.125]])),
             ('kinds', ['list', 'domain', 'domain', 'domain']),
             ('encoding', 'gzip'),
             ('space origin', np.array([11.51329994, 21.80450058, -4.03493023])),
             ('Segment0_Color', '0.945098 0.839216 0.568627'),
             ('Segment0_ColorAutoGenerated', '0'),
             ('Segment0_Extent', '16 548 57 648 21 489'),
             ('Segment0_ID', 'Segment_1'),
             ('Segment0_LabelValue', '1'),
             ('Segment0_Layer', '0'),
             ('Segment0_Name', 'Bone'),
             ('Segment0_NameAutoGenerated', '0'),
             ('Segment0_Tags',
              'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'),
             ('Segment10_Color', '0.847059 0.396078 0.309804'),
             ('Segment10_ColorAutoGenerated', '1'),
             ('Segment10_Extent', '16 548 57 648 21 489'),
             ('Segment10_ID', 'Segment_12'),
             ('Segment10_LabelValue', '11'),
             ('Segment10_Layer', '0'),
             ('Segment10_Name', 'Tympanic Membrane'),
             ('Segment10_NameAutoGenerated', '1'),
             ('Segment10_Tags',
              'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'),
             ('Segment11_Color', '0.333333 0.737255 1'),
             ('Segment11_ColorAutoGenerated', '0'),
             ('Segment11_Extent', '16 548 57 648 21 489'),
             ('Segment11_ID', 'Segment_10'),
             ('Segment11_LabelValue', '12'),
             ('Segment11_Layer', '0'),
             ('Segment11_Name', 'Sinus - Dura'),
             ('Segment11_NameAutoGenerated', '0'),
             ('Segment11_Tags',
              'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'),
             ('Segment12_Color', '0.501961 0.682353 0.501961'),
             ('Segment12_ColorAutoGenerated', '1'),
             ('Segment12_Extent', '193 287 270 326 133 317'),
             ('Segment12_ID', 'Segment_9'),
             ('Segment12_LabelValue', '1'),
             ('Segment12_Layer', '1'),
             ('Segment12_Name', 'EAC'),
             ('Segment12_NameAutoGenerated', '0'),
             ('Segment12_Tags',
              'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'),
             ('Segment1_Color', '0.333333 0.737255 1'),
             ('Segment1_ColorAutoGenerated', '1'),
             ('Segment1_Extent', '16 548 57 648 21 489'),
             ('Segment1_ID', 'Segment_1_2'),
             ('Segment1_LabelValue', '2'),
             ('Segment1_Layer', '0'),
             ('Segment1_Name', 'Scala Tympani'),
             ('Segment1_NameAutoGenerated', '1'),
             ('Segment1_Tags',
              'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'),
             ('Segment2_Color', '0.866667 0.509804 0.396078'),
             ('Segment2_ColorAutoGenerated', '1'),
             ('Segment2_Extent', '16 548 57 648 21 489'),
             ('Segment2_ID', 'Segment_2'),
             ('Segment2_LabelValue', '3'),
             ('Segment2_Layer', '0'),
             ('Segment2_Name', 'Scala Vestibuli'),
             ('Segment2_NameAutoGenerated', '1'),
             ('Segment2_Tags',
              'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'),
             ('Segment3_Color', '0.501961 0.682353 0.501961'),
             ('Segment3_ColorAutoGenerated', '1'),
             ('Segment3_Extent', '16 548 57 648 21 489'),
             ('Segment3_ID', 'Segment_3'),
             ('Segment3_LabelValue', '4'),
             ('Segment3_Layer', '0'),
             ('Segment3_Name', 'Malleus'),
             ('Segment3_NameAutoGenerated', '1'),
             ('Segment3_Tags',
              'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'),
             ('Segment4_Color', '0.784314 0.784314 0.921569'),
             ('Segment4_ColorAutoGenerated', '0'),
             ('Segment4_Extent', '16 548 57 648 21 489'),
             ('Segment4_ID', 'Segment_4'),
             ('Segment4_LabelValue', '5'),
             ('Segment4_Layer', '0'),
             ('Segment4_Name', 'Incus'),
             ('Segment4_NameAutoGenerated', '1'),
             ('Segment4_Tags',
              'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'),
             ('Segment5_Color', '0.847059 0.396078 0.309804'),
             ('Segment5_ColorAutoGenerated', '1'),
             ('Segment5_Extent', '16 548 57 648 21 489'),
             ('Segment5_ID', 'Segment_5'),
             ('Segment5_LabelValue', '6'),
             ('Segment5_Layer', '0'),
             ('Segment5_Name', 'Stapes'),
             ('Segment5_NameAutoGenerated', '1'),
             ('Segment5_Tags',
              'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'),
             ('Segment6_Color', '0.901961 0.862745 0.27451'),
             ('Segment6_ColorAutoGenerated', '1'),
             ('Segment6_Extent', '16 548 57 648 21 489'),
             ('Segment6_ID', 'Segment_6'),
             ('Segment6_LabelValue', '7'),
             ('Segment6_Layer', '0'),
             ('Segment6_Name', 'Vestibulcochlear Nerve'),
             ('Segment6_NameAutoGenerated', '1'),
             ('Segment6_Tags',
              'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'),
             ('Segment7_Color', '0.956863 0.839216 0.192157'),
             ('Segment7_ColorAutoGenerated', '1'),
             ('Segment7_Extent', '16 548 57 648 21 489'),
             ('Segment7_ID', 'Vestibulcochlear Nerve -_1'),
             ('Segment7_LabelValue', '8'),
             ('Segment7_Layer', '0'),
             ('Segment7_Name', 'Facial Nerve'),
             ('Segment7_NameAutoGenerated', '1'),
             ('Segment7_Tags',
              'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'),
             ('Segment8_Color', '0.752941 0.407843 0.345098'),
             ('Segment8_ColorAutoGenerated', '1'),
             ('Segment8_Extent', '16 548 57 648 21 489'),
             ('Segment8_ID', 'Segment_7'),
             ('Segment8_LabelValue', '9'),
             ('Segment8_Layer', '0'),
             ('Segment8_Name', 'Carotis'),
             ('Segment8_NameAutoGenerated', '1'),
             ('Segment8_Tags',
              'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'),
             ('Segment9_Color', '0.847059 0.396078 0.309804'),
             ('Segment9_ColorAutoGenerated', '1'),
             ('Segment9_Extent', '16 548 57 648 21 489'),
             ('Segment9_ID', 'Segment_8'),
             ('Segment9_LabelValue', '10'),
             ('Segment9_Layer', '0'),
             ('Segment9_Name', 'Chorda Tympani'),
             ('Segment9_NameAutoGenerated', '1'),
             ('Segment9_Tags',
              'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'),
             ('Segmentation_ContainedRepresentationNames',
              'Binary labelmap|Closed surface|'),
             ('Segmentation_ConversionParameters',
              'Collapse labelmaps|1|Merge the labelmaps into as few shared labelmaps as possible 1 = created labelmaps will be shared if possible without overwriting each other.&Compute surface normals|1|Compute surface normals. 1 (default) = surface normals are computed. 0 = surface normals are not computed (slightly faster but produces less smooth surface display).&Crop to reference image geometry|0|Crop the model to the extent of reference geometry. 0 (default) = created labelmap will contain the entire model. 1 = created labelmap extent will be within reference image extent.&Decimation factor|0.0|Desired reduction in the total number of polygons. Range: 0.0 (no decimation) to 1.0 (as much simplification as possible). Value of 0.8 typically reduces data set size by 80% without losing too much details.&Fractional labelmap oversampling factor|1|Determines the oversampling of the reference image geometry. All segments are oversampled with the same value (value of 1 means no oversampling).&Joint smoothing|0|Perform joint smoothing.&Oversampling factor|1|Determines the oversampling of the reference image geometry. If it\'s a number, then all segments are oversampled with the same value (value of 1 means no oversampling). If it has the value "A", then automatic oversampling is calculated.&Reference image geometry|0.125;0;0;-11.5132999420166;0;0.125;0;-21.804500579834;0;0;0.125;-4.03493022918701;0;0;0;1;0;569;0;661;0;642;|Image geometry description string determining the geometry of the labelmap that is created in course of conversion. Can be copied from a volume, using the button.&Smoothing factor|0.5|Smoothing factor. Range: 0.0 (no smoothing) to 1.0 (strong smoothing).&Threshold fraction|0.5|Determines the threshold that the closed surface is created at as a fractional value between 0 and 1.&'),
             ('Segmentation_MasterRepresentation', 'Binary labelmap'),
             ('Segmentation_ReferenceImageExtentOffset', '0 0 0')])
    return header

@pytest.fixture
def rawdata() -> np.ndarray:
    fpath = Path('G:/Cochlea/dataset_sieber/ctseg.npy')
    return np.load(fpath)


def test(rawdata, segheader):
    sifter = Sifter.from_sieberdefaults()

    labelarray, segments = sifter.sift(rawdata, segheader)

    metadata_specified_unique = get_unique_label_values(segments)
    # Account for missing background dummy segment.
    metadata_specified_unique.add(0)
    array_specified_unique = set(np.unique(labelarray))
    assert metadata_specified_unique == array_specified_unique, 'label value mismatch'

    print(segments)

    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(ncols=4)
    axes = axes.flat

    z_idcs = [230, 260, 290, 320]

    for idx, ax in zip(z_idcs, axes):
        ax.imshow(labelarray[idx, ...])
    
    plt.show()